# 服务端口
server:
  port: 8081

# 应用名称
spring:
  application:
    name: floworder-resource-service
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/floworder?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1234
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    # openfeign
    openfeign:
      client:
        config:
          floworder-order-service:
            connectTimeout: 2000
            readTimeout: 5000
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated #开启发送端确认机制,消息是否到达交换机
    publisher-returns: true #消息是否路由到队列,要配合template.mandatory: true 一起使用，否则不会回调。
    template:
      mandatory: true #防止消息被 RabbitMQ 静默丢弃
    listener:
      simple:
        acknowledge-mode: manual #手动确认队列消息
        default-requeue-rejected: false # 当消费者监听方法处理消息失败，并且消息被拒绝时，默认不要把这条消息重新放回队列。消费异常后，消息不再回到原队列。如果配置了死信队列，则进入死信队列；如果没有配置死信队列，则消息可能被丢弃。
  # redisson
  redisson:
    address: redis://127.0.0.1:6379
    database: 1
