spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: floworder-order-service
              uri: lb://floworder-order-service
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=1
              metadata:
                title: 订单服务

            - id: floworder-resource-service
              uri: lb://floworder-resource-service
              predicates:
                - Path=/api/reservation/**
              filters:
                - StripPrefix=1
              metadata:
                title: 资源服务
