package com.javaup.dto;

public enum IncidentAnomalyType {
    ORDER_TIMEOUT_INVENTORY_UNRELEASED,
    ORDER_CANCELLED_INVENTORY_UNRELEASED,
    DEAD_LETTER_PENDING,
    ORDER_INVENTORY_STATE_MISMATCH
}
